### ISSUE TITLE
Failed to read from defunct connection IPv4Address(('localhost', 7687)) (IPv4Address(('127.0.0.1', 7687)))

### ISSUE THREAD

**Issue by nebriv** [PlumHound/PlumHound#18]
**Describe the bug**
Hey there!

I'm receiving the following error when trying to run the default tasks:
Failed to read from defunct connection IPv4Address(('localhost', 7687)) (IPv4Address(('127.0.0.1', 7687)))

I have neo4j installed on Kali populated with data. I've verified the data exists and is query-able in Bloodhound. It is hard to tell if this is a critical failure, or if I'm running into some other issue, but the reports are not being populated.

**To Reproduce**
Simply running the default tasks seems to cause the problem.

**Expected behavior**
I would have expected data to be generated :)

**Screenshots**
```
(venv) kali@kali:~/PlumHound$ python PlumHound.py -x tasks/default.tasks -u "neo4j" -p "neo4j"
[*]Building Task List
No data
Failed to read from defunct connection IPv4Address(('localhost', 7687)) (IPv4Address(('127.0.0.1', 7687)))
[*]Beginning Output HTML:reports//Workstations_RDP.html
[*]Beginning Output HTML:reports//CrossDomainRelationships.html
[*]Beginning Output HTML:reports//DA_Sessions.html
[*]Beginning Output HTML:reports//EA_Sessions.html
[*]Beginning Output HTML:reports//Permissions_Everyone.html
[*]Beginning Output HTML:reports//Users_NoKerbReq.html
No data
Failed to read from defunct connection IPv4Address(('localhost', 7687)) (IPv4Address(('127.0.0.1', 7687)))
(venv) kali@kali:~/PlumHound$ 
```

**Desktop (please complete the following information):**
Kali 2020.3
Python 3.8.3

**Comment by direncuyanik** [comment]
I experience exact same issue if i use newest version of neo4j in Windows. 

But in Linux works with no issues : 

 - Linux version 5.7.0-kali1-amd64 (devel@kali.org) (gcc version 9.3.0 (Debian 9.3.0-14), GNU ld (GNU Binutils for Debian) 2.34) #1 SMP Debian 5.7.6-1kali2 (2020-07-01)

- neo4j 4.0.7
- Python 3.8.6

try updating, other required tools in requirements.txt which comes with PlumHound files.

**Comment by Relkci** [comment]
Please test recent master branch (note, execute pip3 install -r requirements.txt first) @nebriv

**Comment by Relkci** [comment]
this is believed to be fixed.
