### ISSUE TITLE
Plumhound Dev - Python Error

### ISSUE THREAD

**Issue by yellow-starburst** [PlumHound/PlumHound#25]
![image](https://user-images.githubusercontent.com/39839623/107901456-a77c4b00-6f11-11eb-8adf-40efb2c8c76a.png)

I've tried python3.8 and python3.7

**Comment by yellow-starburst** [comment]
Also is it possible to upgrade  from six-1.14.0 to six-1.15.0? May be related to this issue
![image](https://user-images.githubusercontent.com/39839623/107901496-c4b11980-6f11-11eb-9c18-55e68dfcb857.png)

**Comment by Relkci** [comment]
Will look into on next review, likely needs to be bumped up on requirements.txt
