### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by Joanthan17** [PlumHound/PlumHound#30]
The Iterable abstract class was removed from collections in Python 3.10.

this causes the following error when trying to run the program on the ubuntu 22.04

![image](https://user-images.githubusercontent.com/72089812/169804103-a9b2905c-5f7f-4078-b2d3-1749a886acf1.png)

might need to update requirements.txt or change the source code a bit to have the following:

`
try:
    from collections.abc import Iterable 
except ImportError:
    from collections import Iterable
`

**Comment by Relkci** [comment]
Is this still an issue?
