### ISSUE TITLE
Weird output 

### ISSUE THREAD

**Issue by Joanthan17** [PlumHound/PlumHound#31]
while running the app i get the following output:

![image](https://user-images.githubusercontent.com/72089812/169850164-d2f27092-4727-47b0-a55b-68ce31b8c8cb.png)

there's nothing in the reports themself.

ENV:
OS - ubuntu 22.04
Neo4j is running
BHD is running

**Comment by Relkci** [comment]
what version of python was this?

**Comment by Relkci** [comment]
Use python 3.9 max, error condition was re-produced on 3.10
upstream bug, will investigate
