### ISSUE TITLE
Start work on migrating to neo4j 5.2 driver

### ISSUE THREAD

**Issue by Relkci** [PlumHound/PlumHound#36]
Start work on migrating to neo4j 5.2 driver

**Comment by Scoubi** [comment]
There was a post from Andy saying Neo4j 5 had performance issue with BH.
They do not recommend upgrading to 5 yet.

**Comment by Relkci** [comment]
I figure at some point 1.7 will lose support with upcoming python versions.  still supported, for now.

it will require a significant re-write when the time comes.  Closing for now.
