### ISSUE TITLE
 'gbk' codec can't decode byte 0xb2 in position 2142: illegal multibyte sequence

### ISSUE THREAD

**Issue by langyajiekou** [PlumHound/PlumHound#48]
Would like to get help from this error?

on 66: 'gbk' codec can't decode byte 0xb2 in position 2142: illegal multibyte sequence
on 67: INFO     ERROR While running job (trying next job in list).
on 67: 'gbk' codec can't decode byte 0xb2 in position 2142: illegal multibyte sequence
on 68: INFO     ERROR While running job (trying next job in list).
on 68: 'gbk' codec can't decode byte 0xb2 in position 2142: illegal multibyte sequence
on 69: INFO     ERROR While running job (trying next job in list).
on 69: 'gbk' codec can't decode byte 0xb2 in position 2142: illegal multibyte sequence
on 70: INFO     ERROR While running job (trying next job in list).
on 70: 'gbk' codec can't decode byte 0xb2 in position 2142: illegal multibyte sequence
on 71: INFO     ERROR While running job (trying next job in list).
on 71: 'gbk' codec can't decode byte 0xb2 in position 2142: illegal multibyte sequence
on 72: INFO     ERROR While running job (trying next job in list).
on 72: 'gbk' codec can't decode byte 0xb2 in position 2142: illegal multibyte sequence
on 73: INFO     ERROR While running job (trying next job in list).
on 73: 'gbk' codec can't decode byte 0xb2 in position 2142: illegal multibyte sequence
on 74: INFO     ERROR While running job (trying next job in list).
on 74: 'gbk' codec can't decode byte 0xb2 in position 2142: illegal multibyte sequence
on 75: INFO     ERROR While running job (trying next job in list).
on 75: list index out of range
         Executing Tasks |██████████████████████████████████████████████████| Tasks 75 / 75  in 2.0s (37.61/s)

**Comment by Relkci** [comment]
I believe this may have possibly been a text encoding issue and fixed here: 
https://github.com/PlumHound/PlumHound/pull/50
h/t @bioless 
Try again? :)

**Comment by Relkci** [comment]
closing as fixed.  thanks
